package br.com.matheusreinheimer.apifeupuda.model;

public enum Breed {
    SIAMES, SPHYNX, PERSA, RAGAMUFFIN, CARACAT, MAINE_COON, KHAO_MANEE, BOBTAIL_AMERICANO, BOBTAIL_JAPONES, 
    SINGAPURA, CYMRIC, MANES, SKOOKUM, TOYGER, AMERICAN_WIREHAIR, TONQUINES, JAVANES, SCOTTISH_FOLD
}
